#!/usr/bin/env python
import random


"""
To use this library first install WF as a large file of words.
For instance, you can use google's 10000 english words like so: 

$ cd ~/lib 
$ git clone http://github.com/first20hours/google-10000-english
$ cd google-10000-english 
$ cat google-10000-english.txt | grep ".....*" > google-10000-english-4+.txt

Then set WF accordingly. 

"""
WF = "/home/francoisbabeuf/lib/google-10000-english/google-10000-english-4+.txt"
SIZE = 8906
password = ""

for i in range(0,4):
    fp = open(WF)
    num = random.randint(0,SIZE)
    for i, line in enumerate(fp):
        if i == num:
            password += line.strip() + " "
            break
    fp.close()

print password
